services:
  # for local dev
  anvil:
    image: ghcr.io/foundry-rs/foundry
    entrypoint: ['anvil']
    command:
      - --host=0.0.0.0
      - --port=8545
    ports:
      - '8545:8545'

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
