### GET ORDER
GET http://localhost:5000/api/orders?status=active&chainId=31337&collection=0xA5f104F8f78d5ba9AEC4a383c0927337Fd4E997B&cursor=1782682188_69dd0c1ac02ad2bc5565a1f0&include=nftCollection&isCollectionBid=false&sortField=end&sortDir=asc&limit=25