### Get settlement by ID
GET http://localhost:5000/api/settlements/6973ba86f0205fa0197d4888

###  List all 
GET http://localhost:5000/api/settlements?limit=50

### By seller
GET http://localhost:5000/api/settlements?seller=0x31F1a4B4f9f7CAD3f21bF9F2c3840C5CcF7B85b9&limit=10

### By date range
GET http://localhost:5000/api/settlements?from=1700000000&to=1800000000&limit=50

