@baseUrl = http://localhost:5000

### Li st settlements
GET {{baseUrl}}/api/settlements?limit=25&include=nftCollection&include=nft

### By seller or buyer (any involvement)
GET {{baseUrl}}/api/settlements?or.seller=<address>&or.buyer=<address>

### Read unique wallets
GET {{baseUrl}}/api/settlements/wallets/count

# GET {{baseUrl}}/api/settlements?buyer=<address>&limit=25

# GET {{baseUrl}}/api/settlements/31337:<orderHash>
