@baseUrl = http://localhost:5000

### List settlements
GET {{baseUrl}}/api/settlements?limit=25

### By seller or buyer (any involvement)
GET {{baseUrl}}/api/settlements?or.seller=<address>&or.buyer=<address>

# GET {{baseUrl}}/api/settlements?seller=<address>&limit=25

# GET {{baseUrl}}/api/settlements?buyer=<address>&limit=25

# GET {{baseUrl}}/api/settlements/31337:<orderHash>
